name = "staketoken"
compatibility_date = "2024-01-15"

# Static site configuration
pages_build_output_dir = "out"

[env.production]
name = "staketoken-prod"

[env.production.vars]
NEXT_PUBLIC_CLIENT_ID = "your-thirdweb-client-id"
NEXT_PUBLIC_DOMAIN = "staketoken.pages.dev"
NEXT_PUBLIC_API_URL = "https://your-backend-api.com"
NEXT_PUBLIC_PRIVATE_KEY = "your-private-key"

# Build configuration for static site
[build]
command = "npm run build"